config/routes.rb
Rails.application.routes.draw do

devise_for :membros  
devise_scope :membro do
  authenticated :membro do
    root :to => 'pedidos#index', as: :authenticated_root
  end
  unauthenticated :membro do
    root :to => 'devise/sessions#new', as: :unauthenticated_root
  end
end

  resources :pedidos
  resources :usuarios

end

app/models/membro.rb
class Membro < ActiveRecord::Base
  #enum role: [:aluno, :ppg]
  
  has_many :pedidos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :membro
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
    has_many :pedidos
    before_save { self.email = email.downcase }
    validates :nome, presence: true, length: { maximum: 60 }
    EMAIL_VALIDO_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    # Mudar a regex acima para terminar com '@cin.ufpe.br'
    
    validates :email, presence: true, length: { maximum: 30 },
                      format: { with: EMAIL_VALIDO_REGEX },
                      uniqueness: { case_sensitive: false }
#    has_secure_password
#    validates :password, presence: true, length: { minimum: 8 }

end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #include Pundit

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
rescue_from Pundit::NotAuthorizedError, with: :membro_not_authorized
    
private
  def membro_not_authorized
    flash[:alert] = "Operação não permitida."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/control_membros_controller.rb
class ControlmembrosController < ApplicationController
    before_action :authenticate_membro!

  def index
    @membros = Membro.all
    authorize @membros
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_membro!
    
  def index?
    membro.ppg?
  end
    
    def index
    end
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_membro!


  # GET /pedidos
  # GET /pedidos.json



#  def index
#    if policy(@membros).index?
#      @pedidos = Pedido.all
#    else
#      @pedidos = current_membro.pedidos
#    end
#  end

#   end
#  end



def index
  @pedidos = Pedido.all
end


  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
    #Iniciando implementação do pdf
   # @pedidos = Pedido.find(params[:id])
    #respond_to do |format|
     # format.html
      #format.pdf do
       #  pdf = Prawn::Document.new
        # pdf.text = "Olá"
       # pdf = ReportPdf.new(@pedidos)
        #send_data pdf.render, filename: 'report.pdf', type: 'application/pdf'
      #end
    #end
    
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end



  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)
    @pedido.membro_id = current_membro.id  
    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Solicitação salva com sucesso.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: 'Solicitação atualizada com sucesso' }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: 'Pedido apagado com successo.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = current_membro.pedidos.find(params[:id])
      #@pedido  = Pedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params.require(:pedido).permit(:cpf, :nome, :email, :nivel, :fone, :ramal, :orient, :coorient, :dep_coor, :ies_coor, :area, :proj_assoc, :titulo, :resumo, :pal_chave, :sala, :data, :hora, :exam1, :exam1_mail, :exam1_dep, :exam1_ies, :exam1_pub, :exam2, :exam2_mail, :exam2_dep, :exam2_ies, :exam2_pub, :exam3, :exam3_mail, :exam3_dep, :exam3_ies, :exam3_pub, :exam4, :exam4_mail, :exam4_dep, :exam4_ies, :exam4_pub, :exam5, :exam5_mail, :exam5_dep, :exam5_ies, :exam5_pub, :exam6, :exam6_mail, :exam6_dep, :exam6_ies, :exam6_pub, :exam7, :exam7_mail, :exam7_dep, :exam7_ies, :exam7_pub, :sup_int, :sup_int_mail, :sup_int_pub, :sup_ext, :sup_ext_mail, :sup_ext_dep, :sup_ext_ies, :sup_ext_pub, :confirma, :usuario_id)
    end
end

app/controllers/usuarios_controller.rb
# class UsuariosController < ApplicationController
#   before_action :set_usuario, only: [:show, :edit, :update, :destroy]
#   before_action :authenticate_membro!

#   # GET /usuarios
#   # GET /usuarios.json
#   def index
#     @usuarios = Usuario.all
#   end

#   # GET /usuarios/1
#   # GET /usuarios/1.json
#   def show
#   end

#   # GET /usuarios/new
#   def new
#     @usuario = Usuario.new
#   end

#   # GET /usuarios/1/edit
#   def edit
#   end

#   # POST /usuarios
#   # POST /usuarios.json
#   def create
#     @usuario = Usuario.new(usuario_params)

#     respond_to do |format|
#       if @usuario.save
#         format.html { redirect_to @usuario, notice: 'Usuário cadastrado com sucesso!' }
#         format.json { render :show, status: :created, location: @usuario }
#       else
#         format.html { render :new }
#         format.json { render json: @usuario.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # PATCH/PUT /usuarios/1
#   # PATCH/PUT /usuarios/1.json
#   def update
#     respond_to do |format|
#       if @usuario.update(usuario_params)
#         format.html { redirect_to @usuario, notice: 'Usuário atualizado com sucesso!' }
#         format.json { render :show, status: :ok, location: @usuario }
#       else
#         format.html { render :edit }
#         format.json { render json: @usuario.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # DELETE /usuarios/1
#   # DELETE /usuarios/1.json
#   def destroy
#     @usuario.destroy
#     respond_to do |format|
#       format.html { redirect_to usuarios_url, notice: 'Usuário excluído com sucesso!' }
#       format.json { head :no_content }
#     end
#   end

#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_usuario
#       @usuario = Usuario.find(params[:id])
#     end

#     # Never trust parameters from the scary internet, only allow the white list through.
#     def usuario_params
#       params.require(:usuario).permit(:cpf, :nome, :email, :nivel, :fone, :ramal, :orient, :coorient)
#     end
# end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/controlmembros_helper.rb
module ControlmembrosHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/control_membros/index.html.erb
<h1>Controlmembros#index</h1>
<p>Find me in app/views/controlmembros/index.html.erb</p>

app/views/dashboard/_aluno_index.html.erb
<h1>ALUNO</h1>

app/views/dashboard/_ppg_index.html.erb
<h1>PPG</h1>

app/views/dashboard/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sistema de Solicitações de Banca Examinadora - 2SBE</h1>

<% if policy(@dashboard).index? %>
    <%= render partial: "ppg_index" %>
<% else %>
    <%= render partial: "aluno_index" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "App2sbe" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
<!--
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">App2sbe</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>
-->
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <!--<div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

     <!-- <footer align="center">
        <p>&copy; Centro de Informática - UFPE<p>
      </footer> -->
      

    </div> <!-- /container -->

  </body>
</html>

app/views/pedidos/edit.html.erb
<%- model_class = Pedido -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pedidos/index.html.erb
<%- model_class = Pedido -%>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
   <li align= "right"><%=link_to "Sair", destroy_membro_session_path, method: :delete %></li>
</div>
      
<table class="table table-striped">
  <thead>
    <tr>
      <!--<th><%= model_class.human_attribute_name(:id) %></th>-->
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:nivel) %></th>
      <th><%= model_class.human_attribute_name(:orient) %></th>
      <!--<th><%= model_class.human_attribute_name(:coorient) %></th>-->
      <!--<th><%= model_class.human_attribute_name(:titulo) %></th>-->
      <th><%= model_class.human_attribute_name(:data) %></th>
      <th><%= model_class.human_attribute_name(:hora) %></th>
      <!--<th><%= model_class.human_attribute_name(:usuario_id) %></th>-->
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pedidos.each do |pedido| %>
      <tr>
        <td><%= pedido.nome %></td>
        <td><%= pedido.email %></td>
        <td><%= pedido.nivel %></td>
        <td><%= pedido.orient %></td>
        <td><%= pedido.data %></td>
        <td><%= pedido.hora %></td>
        <td><%=l pedido.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_pedido_path(pedido), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      pedido_path(pedido),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_pedido_path,
            :class => 'btn btn-primary' %>

app/views/pedidos/new.html.erb
<%- model_class = Pedido -%>
<div class="page-header">
  <h1 align="center"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/usuarios/_form.html.erb
<%= form_for @usuario, :html => { :class => "form-horizontal usuario" } do |f| %>

  <% if @usuario.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @usuario.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :cpf, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cpf, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cpf) %>
  </div>
  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :nivel, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nivel, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nivel) %>
  </div>
  <div class="form-group">
    <%= f.label :fone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :fone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:fone) %>
  </div>
  <div class="form-group">
    <%= f.label :ramal, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :ramal, :class => 'form-control' %>
    </div>
    <%=f.error_span(:ramal) %>
  </div>
  <div class="form-group">
    <%= f.label :orient, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :orient, :class => 'form-control' %>
    </div>
    <%=f.error_span(:orient) %>
  </div>
  <div class="form-group">
    <%= f.label :coorient, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :coorient, :class => 'form-control' %>
    </div>
    <%=f.error_span(:coorient) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                usuarios_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/usuarios/edit.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/usuarios/index.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:cpf) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:nivel) %></th>
      <th><%= model_class.human_attribute_name(:fone) %></th>
      <th><%= model_class.human_attribute_name(:ramal) %></th>
      <th><%= model_class.human_attribute_name(:orient) %></th>
      <th><%= model_class.human_attribute_name(:coorient) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= link_to usuario.id, usuario_path(usuario) %></td>
        <td><%= usuario.cpf %></td>
        <td><%= usuario.nome %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.nivel %></td>
        <td><%= usuario.fone %></td>
        <td><%= usuario.ramal %></td>
        <td><%= usuario.orient %></td>
        <td><%= usuario.coorient %></td>
        <td><%=l usuario.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_usuario_path(usuario), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      usuario_path(usuario),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_usuario_path,
            :class => 'btn btn-primary' %>

app/views/usuarios/new.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/usuarios/show.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:cpf) %>:</strong></dt>
  <dd><%= @usuario.cpf %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @usuario.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @usuario.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nivel) %>:</strong></dt>
  <dd><%= @usuario.nivel %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fone) %>:</strong></dt>
  <dd><%= @usuario.fone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ramal) %>:</strong></dt>
  <dd><%= @usuario.ramal %></dd>
  <dt><strong><%= model_class.human_attribute_name(:orient) %>:</strong></dt>
  <dd><%= @usuario.orient %></dd>
  <dt><strong><%= model_class.human_attribute_name(:coorient) %>:</strong></dt>
  <dd><%= @usuario.coorient %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              usuarios_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_usuario_path(@usuario), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              usuario_path(@usuario),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/welcome/index.html.erb
<h1>LOGIN WELCOME</h1>

<html>
    
<body>
   
<h3 align='center'>Sistema de Solicitação de Banca Examinadora - 2SBE <h3>
    
    
        <ul>
        <li><%=link_to "Sair", destroy_membro_session_path, method: :delete %></li>
        </ul>
    
    
        <li><%=link_to "Login", membro_session_path %></li>
        <li><%=link_to "Cadastrar", new_membro_registration_path %></li>
   
       
 
    
</body>




</html>